### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gloriaJun** [gloriaJun/gloriaJun.github.io-archived#2]
## Javascript

- [ ] functional programming을 이용하여 유틸리티 만들기
    - https://github.com/gloriaJun/js-utils-fp

## Javascript with css

- https://www.youtube.com/channel/UC_s1FC7s5YVwDImzv-WG93Q/playlists
- https://www.inflearn.com/course/interactive_web

## react

- [ ] https://github.com/gloriaJun/react-realworld-example-app
   - hook
   - reducer
   - saga
   - context

## boilerplate

프로젝트 생성마다 기반으로 사용할 보일러프로젝트 만들기

- [ ] https://github.com/gloriaJun/boilerplate-react-webpack
    -  [ ] 하나의 리포에 담아두기
        - react-custom-webpack
        - react-with-cra
        - react-typescript
        - vanila
- [ ] 아래의 설정들 포함하기
   - [ ] webpack
   - [ ] eslint - eslint airbnb
   - [ ] prettier
